### ISSUE TITLE
Wrong RSA PSS verification result

### ISSUE THREAD

**Issue by karussellbremser** [Legrandin/pycryptodome#258] opened 2019-01-18 13:09 UTC
As the title says. Signature is generated by an external source and can be verified successfully with bouncycastle. pycryptodomex (3.7.2) yields a fail result. Digest algorithm is SHA512. In the following hex string, the following data is encoded: message, signature, key modulus, key public exponent. Each encoded as "byte length (2 bytes) || value". (Saltlength is 0 btw, but this is not needed as input parameter.)

00089f4088ba3c20926201429e3984c46c1b6e52e86d2ccfb52a7f461af34d5b7d87b78dbe600b6acc93fe07ad94c02abb2ec4d6db021c28174228ba17c3c4485e0a9a5ce10a592ee378460cefcfa0358d59cdb11e769d5bd5b6ce56d578d5964ceaacec741890bd8ff3459dccc17e704d78a77a66f85a29027066dc421b8af577466d7c60479212d8f7c837547afe1b82ef9de80b76e2c1ce3b860b80489d408a1cac2c96668709d6fd6e65912a00ac981a50be35e84beaa664a617001ae2acf31d01ec85f557eecf3f7815eb855911c5745819e58781bf7c9af8fd7fa9d3dd3af69c52fd54484e28a84bfa7429a0c9da40c95a4fa12dee837a957f2dc09fe465bd34ba555ebed2492f58074cb18e0dbdb3c621ffc8213999f3df093d667a0574360e945123d0c7ec924e1d777dd8f91fb4a1b5ea7c88f4b3abb8b7d00832cf5e13d7bb55c87bdbfe8e82f5f4db0142c9d82b476efdab5b973cbeaa8da106c0e729cda0bed65502a0ddc4869afbdc795cfbdd5c258c8b69a48cf5b3b3049e2973b0c8a628bbd71cf339e5fb8b7e170e29d4df0c771d1d15d27423e6715a00642593a2f8a7b99f0febdb269e8f0583ab36d2742a0ace990335a5af9f3e9df937e967ad0ef14f4d5b3bc7f0ab5cb2c86d299d5a3a7d4cd4e26adc20e7f4aab630e7a2bf485c21d783a42f9e8a313b8b10476b41f403768be15c2d2aae058b0e0d654bb09b3111408ab0f57fe02299553951739a11e1ae74695272dfbb3a205299b8c57bbbf3cd758faceb43f69560925db3d94bb8a66b47d934702d712fc667a3e6980af7a73e6e1ce91fb26f5642053ebd65a296dceb954db0aebe47ac80be393f7b50929f9b30134b85e10aab2580d3233864c25b3b18a84c0bb31d158b33ccd3bf6c63608d254c1f9bb4cdcc2ac3a0a6c10003010001

**Comment by Legrandin** [comment] 2019-01-18 14:15
Which hash algorithm are you using for MFG1? Also SHA-512?

**Comment by karussellbremser** [comment] 2019-01-18 14:33
The signature comes from a Javacard implementation, see https://docs.oracle.com/javacard/3.0.5/api/javacard/security/Signature.html#ALG_RSA_SHA_512_PKCS1_PSS It is not possible to specify the MFG1 there, so I assume that it's also SHA512. Also, I did not specify this for the bouncycastle verification, so whatever bouncycastle used (again, probably SHA512) should be correct.

**Comment by karussellbremser** [comment] 2019-01-18 14:39
What I should add: the above signature uses a 2576 bit key. The pycryptodome verification fails with this key size repeatedly with different message/key data. Everything works fine however when the key size is changed to 576 bit (while still using SHA512 and 0 bit salt). So the MFG1 selection should not be the problem here.

**Comment by Legrandin** [comment] 2019-01-18 22:17
The signature checks out if you create the verifier as:

    verifier = pss.new(key, salt_bytes=0)

MGF1 is therefore the standard one, based on SHA-512.

**Comment by karussellbremser** [comment] 2019-01-19 10:11
Ah, okay. I just had a look at the corresponding RFC 8017 again: In contrast to my previous assumption, the saltlength parameter is actually a required parameter for the verification. So the behavior that you describe actually matches the RFC. No bug here.

However: As I said above, I was able to verify a 576 bit signature with SHA512 and 0 bit salt without specifying the salt length in the constructor as you describe above. THIS then is a bug, even a more severe one because it is a false-positive verification. The verification should assume a 512-bit salt. If you follow the steps in RFC 8017, section 9.1.2 closely, at latest in step 14 the procedure should fail, as the wrong salt should have been used before (a 512-bit salt instead of 0-bit). Probably it would crash even earlier, e.g. in steps 3 or 10.

Unfortunately, I do not have access to the 576-bit signature in question right now. I will post it on Monday. I think this issue is definitely a bug and should be addressed.

**Comment by Legrandin** [comment] 2019-01-19 21:50
Yes, you are correct, that is a bug and needs a fix, and of course thanks for pointing it out (no need to post the 576-bit signature - I think it is clear where the problem is).

**Comment by Legrandin** [comment] 2019-01-20 12:47
Fixed in v3.7.3

**Closed by Legrandin** 2019-01-20 12:47 UTC
