### ISSUE TITLE
Can you publish a python 3.8 wheel?

### ISSUE THREAD

**Issue by ptarjan** [Legrandin/pycryptodome#612] opened 2022-04-07 20:32 UTC
I'd like to not have to build you from source since your package contains some `.so` files which aren't reproducible across machines. Can we get a wheel added please?

**Comment by Varbin** [comment] 2022-04-08 12:54
PyCryptodome does use so called ABI3 wheels containing only `.so` files compatible with all Python versions since Python 3.5 (individual shared librares inside the wheels do have the `.abi3.so` extension). See #458 or #537 for details. Any fairly recent version of pip should pick them up. Linux wheels are additionally build with the `manylinux(1|2010|2014)` which are only linked against "ancient" glibc versions and thus should work with all Linux distributions since CentOS 5 (sic!) that use glibc.

If they for some reason do not work as intended please provide some more details.

**Comment by ptarjan** [comment] 2022-04-08 18:42
Thanks for the update. I'll dig in on my side as to why exactly we aren't getting them. Here is the list of non-hermetic things showing up on my build systems (incase it helps)
```
Crypto/Cipher/_ARC4.cpython-38-x86_64-linux-gnu.so 3e262f83fdc352984a205c1f3b713391ce5c97eb62be653b4bbdbb6b83604d6d
Crypto/Cipher/_ARC4.cpython-38-x86_64-linux-gnu.so 8ebb8c4da0874cca8ff47c2cdd3a5db1a424300bd0936a1cd813e5f61f1e7c35
Crypto/Cipher/_Salsa20.cpython-38-x86_64-linux-gnu.so 1b91a82c0e2d6dbe0e3885d565ace65c057d2a394e465db3e51f52386ae7deab
Crypto/Cipher/_Salsa20.cpython-38-x86_64-linux-gnu.so 9d6288623766162f9bf5aac211f622be5a25c6eb1b925e2b28b8eeac4cfdc47c
Crypto/Cipher/_chacha20.cpython-38-x86_64-linux-gnu.so 0acfb19724bf23eb81cb52f021ff6ece7b4fddbec8983acc3a24d31d7eee0ba8
Crypto/Cipher/_chacha20.cpython-38-x86_64-linux-gnu.so 4d4c99de9b873378411c7d4e25744bed4d0e8a61185cb498d66b2794aefe7b60
Crypto/Cipher/_raw_aes.cpython-38-x86_64-linux-gnu.so dac58e8ba554dbe61460b826bd598943c0c2383088e09563328eade9e91c794c
Crypto/Cipher/_raw_aes.cpython-38-x86_64-linux-gnu.so fd5853a089987e12d07f6d9b808560575e3fcc4815f8001c662ca185af3aa83e
Crypto/Cipher/_raw_aesni.cpython-38-x86_64-linux-gnu.so 23dcec04bfd0a0494538863ebab6b5e7f1323ebdf3d79fb6107205ebae890688
Crypto/Cipher/_raw_aesni.cpython-38-x86_64-linux-gnu.so 5ad92b404e5e82e8ce91c10a1622ebdabd5c0eec50537006d66e5e43481627ce
Crypto/Cipher/_raw_arc2.cpython-38-x86_64-linux-gnu.so ad366690fc52794fd239f237be38939f5f323a2fbf83c56d6febdc58c1ee5cb4
Crypto/Cipher/_raw_arc2.cpython-38-x86_64-linux-gnu.so fffd692313ac38eb0ac3b9cd52be91927975b5dc5b4490bd74dd90174fbb4b75
Crypto/Cipher/_raw_blowfish.cpython-38-x86_64-linux-gnu.so cf0a20b3104088159ced17bf03335674b09c4cb2340e7ee6aad3175d61e42a55
Crypto/Cipher/_raw_blowfish.cpython-38-x86_64-linux-gnu.so ee5e30af721a0de567c66048a2ee77c838efc56d973a1800bd077e26d609edea
Crypto/Cipher/_raw_cast.cpython-38-x86_64-linux-gnu.so 28a1ff8cd99dcb982230c1f9f60f01b006d289dba6a8344d8fff7b803ede4afc
Crypto/Cipher/_raw_cast.cpython-38-x86_64-linux-gnu.so eefdea2ad3c4a8e4fc141b65fa2d6f998f77dfd9a455ddf1ef21f5e361d92202
Crypto/Cipher/_raw_cbc.cpython-38-x86_64-linux-gnu.so 8ee2e82cd4e5579a7ccfab0f702a261e5ac3c413afc7880292adb520557cadf9
Crypto/Cipher/_raw_cbc.cpython-38-x86_64-linux-gnu.so b3e7ecb26e2187abaa5855320d87ce1d6ac13bd437a6a73373fb246e0e8324eb
Crypto/Cipher/_raw_cfb.cpython-38-x86_64-linux-gnu.so 79f1190d3e203e5afa16445d4f17a5d295361b7589e9db5f7841086d9bbd9053
Crypto/Cipher/_raw_cfb.cpython-38-x86_64-linux-gnu.so e9e5fc1f89ae7f605cb139e11e2e3d508ebb72b8d76eb40c1af5c006b21c094c
Crypto/Cipher/_raw_ctr.cpython-38-x86_64-linux-gnu.so 32344cba79b29e75c0326eeff41c563f5c9055bedbb803fa3eee878b391b3394
Crypto/Cipher/_raw_ctr.cpython-38-x86_64-linux-gnu.so d8e6c738ed12bf00b3ad831dc67dfc59c7e0a095d4f0050f8ecbfc2aefbd1215
Crypto/Cipher/_raw_des.cpython-38-x86_64-linux-gnu.so 4a9f5c2745d7bd2bf1cc1d7348719bea323c5735260c0767960c25c460e7a459
Crypto/Cipher/_raw_des.cpython-38-x86_64-linux-gnu.so 8604a8c6d46205fe1d3a994ea4c0113cd7d25937857f436f84dbb18ed94ac426
Crypto/Cipher/_raw_des3.cpython-38-x86_64-linux-gnu.so 93b24c6acd782242ed35a424d0370ffad817e6183e454245dc2c14711bbe1223
Crypto/Cipher/_raw_des3.cpython-38-x86_64-linux-gnu.so c27cba13bf6e6bd25ed5a4d5da77522265069c5bca69691e0d613a45fe9f594f
Crypto/Cipher/_raw_ecb.cpython-38-x86_64-linux-gnu.so 36c4a3dff90cae718935cf8b581beff7867947db03183e2e8780c53151ad0448
Crypto/Cipher/_raw_ecb.cpython-38-x86_64-linux-gnu.so af29e0b677e4473e4967a58cb870d04efe806a741b977b552cb6a0764d23e163
Crypto/Cipher/_raw_ocb.cpython-38-x86_64-linux-gnu.so 945f615bde201a1f1ec3051f8ddb346c00dfaec8417daac66c752d3abd4393c1
Crypto/Cipher/_raw_ocb.cpython-38-x86_64-linux-gnu.so b386bdcbc2a639ab9c5f66addcb58a64f1a38a1a23ceee0af9a9f55cd7523c4f
Crypto/Cipher/_raw_ofb.cpython-38-x86_64-linux-gnu.so 2c990a22577a6782d65ddc3b37b52792c04c5a3d684133319c560ce1871f52e0
Crypto/Cipher/_raw_ofb.cpython-38-x86_64-linux-gnu.so 9903dcbf5eec399b7810a5a48ee6774a2e2a2401febc0ff2df60376655099ad7
Crypto/Hash/_BLAKE2b.cpython-38-x86_64-linux-gnu.so 3e08c21cf57305a174357b7747704ed27958ef77edb2e4b5479dafd288399570
Crypto/Hash/_BLAKE2b.cpython-38-x86_64-linux-gnu.so 4d573352c8ae8e0353831a6724dd88a82e0857dfac0abff0e5340661453761f0
Crypto/Hash/_BLAKE2s.cpython-38-x86_64-linux-gnu.so 5f83340e6dbdfdcb0d918d36ab27ecdb06a1f2833547b57e7f373eda76a6137d
Crypto/Hash/_BLAKE2s.cpython-38-x86_64-linux-gnu.so b0bd66382d1cfbe819d12c519c008fd853214a952e9b815b123431ee1736a202
Crypto/Hash/_MD2.cpython-38-x86_64-linux-gnu.so 7915f75308071e30643f5573d5ff554b9a7252f8a3e683b53a260f4bcbd18ba2
Crypto/Hash/_MD2.cpython-38-x86_64-linux-gnu.so c94f30cb4422ca05629ea1e48c6acd461ed748a1c43c7271a20351ca15cb6c0b
Crypto/Hash/_MD4.cpython-38-x86_64-linux-gnu.so 75c561d5ca3dc2d412dcb2f7212edc65e5358892d359da651bd511237da22708
Crypto/Hash/_MD4.cpython-38-x86_64-linux-gnu.so 9599136f3b0be3fbc846cf776c0c28d35b65041acaca2521724d75e51c3be1ed
Crypto/Hash/_MD5.cpython-38-x86_64-linux-gnu.so 58447771c21a25fb7f71c4e293476d1928319998a15f7f522cd8473b17ec3e9a
Crypto/Hash/_MD5.cpython-38-x86_64-linux-gnu.so 877d9700aaf2eb8a342895f873b12041a093af5298cffcdb21843762447aafb5
Crypto/Hash/_RIPEMD160.cpython-38-x86_64-linux-gnu.so 28c0f12065f7ef9218077e6369b1a7571a378b1a395b045d7cbb63dcdcc949eb
Crypto/Hash/_RIPEMD160.cpython-38-x86_64-linux-gnu.so e2d735fb15034f0ae5ac9af4efbee3f510f4891617310478deda50505fc6c4c0
Crypto/Hash/_SHA1.cpython-38-x86_64-linux-gnu.so 1bffe00ac5cf5f86962fdc641ded0ee4b00de28ea88cf87770abd14c7e617f4f
Crypto/Hash/_SHA1.cpython-38-x86_64-linux-gnu.so 76eceb15f740e9cc4a5185c877fccf1990109d4948018f7c149950029ed9e14b
Crypto/Hash/_SHA224.cpython-38-x86_64-linux-gnu.so 3eedbe161a145d66fc8e1e8877a31d90a6e9720d3fd0db6230cd0b2c88df64a7
Crypto/Hash/_SHA224.cpython-38-x86_64-linux-gnu.so 83ec04716240ca56092f78fb2024b27a4b40b13dfdec1ae3772fcfaa1cdbef2f
Crypto/Hash/_SHA256.cpython-38-x86_64-linux-gnu.so 1f05e3b8bccfa1843cb51b7342ee8169c03dedca54e893f79cce217aae8962a1
Crypto/Hash/_SHA256.cpython-38-x86_64-linux-gnu.so e03358196ed155058f8850e001f11ca921fff57fb73994bd11a11050df4f0f60
Crypto/Hash/_SHA384.cpython-38-x86_64-linux-gnu.so 0cceaaff5f52960610c3b4af2d26071f180b8fb41327c2690fb9f2e75d364b39
Crypto/Hash/_SHA384.cpython-38-x86_64-linux-gnu.so a9d90c10923918844480ae46fc14de3ef82b5d31ff0605aa5c76c9f2b741983d
Crypto/Hash/_SHA512.cpython-38-x86_64-linux-gnu.so a2bc051cb79413f91b0fc40525a7667e3d8d9e07983f4b0f527cd8a8f2612ddc
Crypto/Hash/_SHA512.cpython-38-x86_64-linux-gnu.so c1397d3f0c27486399b8df9e8acdf976e49bddc284a93e2c70ef683cc6163dba
Crypto/Hash/_ghash_clmul.cpython-38-x86_64-linux-gnu.so 1263a4a663dd0c26d564fd8adf0804a81e091ded99e3bf95e4a66bb3b2ace9ee
Crypto/Hash/_ghash_clmul.cpython-38-x86_64-linux-gnu.so 22b06a34c061291a50b5dccb73ef66cb356b987bf33104a9ce8a56603bad8d0b
Crypto/Hash/_ghash_portable.cpython-38-x86_64-linux-gnu.so 8ba274807eed29ab7ef0b9eceee98ab48f69e6f26c3a48e4eb097180a95221ff
Crypto/Hash/_ghash_portable.cpython-38-x86_64-linux-gnu.so ed1d4ceb6067a4fb5af899217d8e1c79938f3917422c7b0c974e17b7e5596b76
Crypto/Hash/_keccak.cpython-38-x86_64-linux-gnu.so adaa647cc1be1c143054a21e268bc701b97c60388167c2117dcb60bbb38192e2
Crypto/Hash/_keccak.cpython-38-x86_64-linux-gnu.so eecf3129d670d1237468247a43d48c066073759445291f2e2459fdbcbb48667c
Crypto/Hash/_poly1305.cpython-38-x86_64-linux-gnu.so 07e7c6b0ac938574589055f4ebd9de01bff77e87c2993b9a3f9d67878ae8d2fe
Crypto/Hash/_poly1305.cpython-38-x86_64-linux-gnu.so 95200d3d0cda4c7fe037ef24498c676c9e2b93dd46cd141c1174b9c2df54e5aa
Crypto/Math/_montgomery.cpython-38-x86_64-linux-gnu.so 3b65fda5bbe68342592adc6b8b381731cf0a0e925436e8f577b5d0c57c1572f4
Crypto/Math/_montgomery.cpython-38-x86_64-linux-gnu.so 532d0fa697ae0cfc20172ab301787bafd64b1c28f239a27f00d7c4ed7783645c
Crypto/Protocol/_scrypt.cpython-38-x86_64-linux-gnu.so 4723c1445e5b8d57560de1e5444fe67086bada67e879e6f174222a40f3da7d62
Crypto/Protocol/_scrypt.cpython-38-x86_64-linux-gnu.so c7df6ec1a8704805bc95231d2c57e6bb6b81dd3fac0fdf656f8b0beeb45b5f05
Crypto/Util/_cpuid_c.cpython-38-x86_64-linux-gnu.so 03e2395efc227137f2afbae6acb0683d9ea1368c60f377989e88f6618b16f8c3
Crypto/Util/_cpuid_c.cpython-38-x86_64-linux-gnu.so 5142e5edc279b88f57586ab8a6fdbbd5ba4c0d2bb674226c7ee4568dd29dbd06
Crypto/Util/_strxor.cpython-38-x86_64-linux-gnu.so 0643845b4c58dd6297d0764c16912102731e2815af22ca846a32419e41e8c2af
Crypto/Util/_strxor.cpython-38-x86_64-linux-gnu.so 601825192cbfe98684237291635693b46694797f2aa1293c92aaad60221ac712
```

**Comment by ptarjan** [comment] 2022-04-08 20:27
I think the reason my `pypi` is not finding it is because on https://pypi.org/project/pycryptodome/3.7.3/#files there isn't anything tagged as `py38`. I see things tagged `cp37` but not `cp38`. If your code makes version agnostic `.so` files, can you just duplicate tag it for all the versions of python which are in wide-use?

**Comment by Varbin** [comment] 2022-04-08 20:29
@ptarjan 3.7.3 is quite outdated. The newest is [3.14.1]( https://pypi.org/project/pycryptodome/3.14.1/#files). ABI3 wheels were introduced in 3.10.1.

**Comment by ptarjan** [comment] 2022-04-08 20:45
Aha! Ok, so you were only talking about your newer packages and not your older ones. I see this started in 3.9.1:
```
# pip install --only-binary=:all: pycryptodome==3.8.0
ERROR: Could not find a version that satisfies the requirement pycryptodome==3.8.0 (from versions: 3.9.1, 3.9.2, 3.9.3, 3.9.4, 3.9.6, 3.9.7, 3.9.8, 3.9.9, 3.10.1, 3.10.3, 3.10.4, 3.11.0, 3.12.0, 3.13.0, 3.14.0, 3.14.1)
ERROR: No matching distribution found for pycryptodome==3.8.0
```

I guess I now have to embark on an upgrade migration, unless you'd like to back-publish `.so` files to these older ones :)

**Comment by alexeagle** [comment] 2022-04-08 20:45
Looks like a newer version is required.
```
% docker run --rm -it --entrypoint=/bin/sh python:3.8.13
# pip install --only-binary=:all: pycryptodome==3.8.0
ERROR: Could not find a version that satisfies the requirement pycryptodome==3.8.0 (from versions: 3.9.1, 3.9.2, 3.9.3, 3.9.4, 3.9.6, 3.9.7, 3.9.8, 3.9.9, 3.10.1, 3.10.3, 3.10.4, 3.11.0, 3.12.0, 3.13.0, 3.14.0, 3.14.1)
ERROR: No matching distribution found for pycryptodome==3.8.0

# pip install --only-binary=:all: pycryptodome==3.9.1

Collecting pycryptodome==3.9.1
  Downloading pycryptodome-3.9.1-cp38-cp38-manylinux1_x86_64.whl (9.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 2.8 MB/s eta 0:00:00
Installing collected packages: pycryptodome
Successfully installed pycryptodome-3.9.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

**Comment by Legrandin** [comment] 2022-12-01 10:29
Closing as wheels for all supported Python 3 versions are available, if one picks a new-ish release or Pycryptodome (for a supported architecture).

**Closed by Legrandin** 2022-12-01 10:29 UTC
