### ISSUE TITLE
Module Initialization Error - Crypto.Hash._MD5

### ISSUE THREAD

**Issue by vijayrcse** [Legrandin/pycryptodome#204] opened 2018-09-07 12:35 UTC
Hi
I am using pyjks in my aws lambda function. pyjks internally dependent on pycryptodome

When i do "import jks" in my python script i am getting the below error. Please note that i have used virtualenv to package my lambda deployment to aws. 

Please advise on this 

**_module initialization error: Cannot load native module 'Crypto.Hash._MD5': Trying '_MD5.cpython-36m-x86_64-linux-gnu.so': /var/task/Crypto/Util/../Hash/_MD5.cpython-36m-x86_64-linux-gnu.so: cannot open shared object file: No such file or directory, Trying '_MD5.abi3.so': /var/task/Crypto/Util/../Hash/_MD5.abi3.so: cannot open shared object file: No such file or directory, Trying '_MD5.so': /var/task/Crypto/Util/../Hash/_MD5.so: cannot open shared object file: No such file or directory_**

**Comment by jlutz777** [comment] 2018-11-08 18:21
Did you figure this out? I ran into a similar problem where it seems to be looking for _MD5.cpython-34m-x86_64-linux-gnu.so, but there is no such file. Instead I have _MD5.cpython-34m.so. The so files all seem to be named incorrectly.

Pardon my ignorance. I'm not sure how all of this works.

**Comment by jlutz777** [comment] 2018-11-12 12:34
In case it helps someone in the future, I eventually pip uninstalled pycryptodome and pycrypto and then went into my site-packages and manually deleted Crypto and anything I found related to pycrypto or pycryptodome. I then reinstalled pycryptodome, and it worked. My theory is something wasn't getting cleaned up from a previous install.

**Comment by Legrandin** [comment] 2019-04-04 09:49
Duplicate of https://github.com/Legrandin/pycryptodome/issues/69

**Closed by Legrandin** 2019-04-04 09:49 UTC
