### ISSUE TITLE
warning: no support for Intel AESNI instructions unable to execute

### ISSUE THREAD

**Issue by nivong** [Legrandin/pycryptodome#27] opened 2016-07-29 11:30 UTC
### Expected Behavior
Install requirments

### Actual Behavior
trows error:
```
warning: no support for Intel AESNI instructions
unable to execute '/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ccache-gcc': No such file or directory
error: Setup script exited with error: command '/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ccache-gcc' failed with exit status 1

### Steps to Reproduce
I have a synology NAS and I have tried the following commands to get it working:
```
sudo pip install -r ./requirements.txt
also tried:
while read line; do sudo easy_install $line; done < requirements.txt

It looks like an build error for the linux kernel. 

### Other Information
OS: Synology Linux DSM 6.x
Git Commit: latest release

### Similair issues:
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/945
https://github.com/PokemonGoF/PokemonGo-Bot/issues/1612

**Comment by Legrandin** [comment] 2016-07-30 22:26
This seems to be related to the compiler setup.

See also [this issue](https://github.com/farcepest/MySQLdb1/issues/37): same error message for a totally different library.

It has nothing to do with AESNI: a warning message about AESNI just happens to be printed right before the problem is encountered.

**Comment by Legrandin** [comment] 2016-10-16 21:12
Closing this issue as the root cause seems external.

**Closed by Legrandin** 2016-10-16 21:12 UTC
