### ISSUE TITLE
Wrong argument type in PBKDF2 function

### ISSUE THREAD

**Issue by r4nx** [Legrandin/pycryptodome#127] opened 2018-02-03 11:26 UTC
In [PBKDF2 function](https://github.com/Legrandin/pycryptodome/blob/99c27a3b9e8a884bbde0e88c63234b669d4398d8/lib/Crypto/Protocol/KDF.py#L97) `salt` type is string, but if I set, for example, `'123321'` as a salt, I am getting an error:
```
File "D:\Programs\Python\Python36\lib\site-packages\Crypto\Protocol\KDF.py", line 136, in PBKDF2
    s = [ prf(password, salt + struct.pack(">I", i)) ] * 2
TypeError: must be str, not bytes
```

`struct.pack(">I", i)` returns bytes and you cannot concatenate string and bytes, so `salt` type should be bytes.

**Comment by Legrandin** [comment] 2018-02-03 16:28
Thanks for reporting! I close this bug report as it is a duplicate of #66 (and yes, it needs to be fixed).

**Closed by Legrandin** 2018-02-03 16:28 UTC
