### ISSUE TITLE
Will this module support Free Threading?

### ISSUE THREAD

**Issue by zenghuan123** [Legrandin/pycryptodome#821] opened 2024-07-17 02:49 UTC
When I run "python3.13t -m pip install pycryptodome,", It occurred error。python3.13t is a build  of Python3.13.0b3 with  the "--disable-gil" option。

**Comment by Legrandin** [comment] 2024-08-12 16:03
Duplicate of https://github.com/Legrandin/pycryptodome/issues/813, which is solve now (in master).

**Closed by Legrandin** 2024-08-12 16:03 UTC
Labels: duplicate
