### ISSUE TITLE
ModuleNotFoundError: No module named 'Crypto.Util.strxor' (Python 3.9)

### ISSUE THREAD

**Issue by dFNSHyVB** [Legrandin/pycryptodome#574] opened 2021-11-14 14:01 UTC
Hi,

when I used the pycryptodome module with Python 3.8, everything worked as expected (and everything still works when I explicitly run the script with Python 3.8). I'm using Ubuntu 20.04 btw.

However running the _same_ code with Python 3.9, this import:

> from Crypto.Protocol.KDF import PBKDF2

will raise this exception:

> ModuleNotFoundError: No module named 'Crypto.Util.strxor'

When I run this:

> import Crypto.Util
> print(Crypto.Util.__ all __)

the output is:

> ['randpool', 'RFC1751', 'number', 'strxor', 'asn1']

So strxor seems to exist, yet cannot be imported for any reason.

When I run this:

> from Crypto.Cipher import Blowfish

I get this error:

> ImportError: cannot import name '_Blowfish' from 'Crypto.Cipher' (/usr/lib/python3/dist-packages/Crypto/Cipher/ __ init __.py)

(Note that I import "Blowfish" and the ImportError says that "_Blowfish" (with a leading underscore) cannot be imported.)

Looking into the file /usr/lib/python3/dist-packages/Crypto/Cipher/__ init __.py,
__ all __ does contain "Blowfish":

>__ all __ = ['AES', 'ARC2', 'ARC4',
>           'Blowfish', 'CAST', 'DES', 'DES3',
>           'XOR',
>           'PKCS1_v1_5', 'PKCS1_OAEP'
>           ]

(Same thing happens when I try to import AES, DES or whatever module.)

Following the advice on this site:

https://pycryptodome.readthedocs.io/en/latest/src/faq.html#why-does-strxor-raise-typeerror-argument-2-must-be-bytes-not-bytearray

I tried

> pip uninstall crypto
> pip uninstall pycryptodome
> pip install pycryptodome

which didn't help.

Running this:

> pip uninstall pycrypto

leads to this:

> ERROR: Cannot uninstall 'pycrypto'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

According to

> pip list --outdated

everything is up to date.

Does anyone have any idea what is going on?

Google didn't help, am I the only one experiencing this?

**Comment by Varbin** [comment] 2022-01-20 22:24
Well you currently have *both* PyCrypto and PyCryptodome installed - the former is likely provided by your system's package manager and thus you should not remove it. *Additionally* Ubuntu's python3.8 and python3.9 share some package import paths (namely `/usr/lib/python3/dist-packages/`), thus 3.9 tries to load the a 3.8 binary extension, which does not work.

To avoid interference of your operating system's packages and packages installed with pip, use *virtual environments*. You can create one with `python3 -m venv your_venv_name` and then tell your current shell to use the virtual environment with `source /path/to/created/your_venv_name/bin/activate` and then install pycryptodome in your venv with pip like you normally would do.

**Comment by Legrandin** [comment] 2022-06-06 19:48
Closing this as it is indeed likely caused by `pycrypto` being installed together with `pycryptodome`.

**Closed by Legrandin** 2022-06-06 19:48 UTC
