### ISSUE TITLE
Build fails on some systems: src/multiply_32.c:53:5: error: use of undeclared identifier '__m128i'

### ISSUE THREAD

**Issue by yurivict** [Legrandin/pycryptodome#125] opened 2018-01-31 19:00 UTC
3.4.7 used ```__m128i``` in src/AESNI.c, but it had ```#include <wmmintrin.h>```.
Now 3.4.8 also uses ```__m128i``` in ```src/multiply_32.c``` but it doesn't have ```#include <wmmintrin.h>```.

I recommend you add this include and make another release: https://github.com/Legrandin/pycryptodome/pull/124

**Comment by Legrandin** [comment] 2018-01-31 22:05
The inclusion of `intrin.h` should be sufficient to provide `__m128i`, but that does not happen because (I think) gcc does not get the `-msse2` flag on the command line for certain 32-bit platforms. The fix for this last issue is in commit e8fab64d74b193eca608013090d6872543ced450, so I prefer to just apply that. I will release a bugfix release asap.

**Comment by yurivict** [comment] 2018-01-31 22:19
Yes, please fix this. This holds the FreeBSD port update.

**Comment by pvizeli** [comment] 2018-02-01 09:42
I think that fix this too #123. It look like a SSE bug.

**Comment by Legrandin** [comment] 2018-02-01 21:07
This should be fixed in v3.4.9. Closing.

**Comment by alxchk** [comment] 2018-11-29 09:32
Latest from pip

```
  src/multiply_32.c(69) : error C2065: '__m128i' : undeclared identifier
    src/multiply_32.c(69) : error C2146: syntax error : missing ';' before identifier 'r0'
    src/multiply_32.c(69) : error C2065: 'r0' : undeclared identifier
    src/multiply_32.c(69) : error C2065: 'r1' : undeclared identifier
    src/multiply_32.c(84) : error C2065: 'r0' : undeclared identifier
    src/multiply_32.c(84) : error C2164: '_mm_set1_epi32' : intrinsic function not declared
    src/multiply_32.c(85) : error C2065: 'r1' : undeclared identifier
    src/multiply_32.c(85) : error C2164: '_mm_cvtsi32_si128' : intrinsic function not declared
    src/multiply_32.c(88) : error C2065: '__m128i' : undeclared identifier
    src/multiply_32.c(88) : error C2146: syntax error : missing ';' before identifier 'r10'
    src/multiply_32.c(88) : error C2065: 'r10' : undeclared identifier
    src/multiply_32.c(88) : error C2065: 'r11' : undeclared identifier
    src/multiply_32.c(88) : error C2065: 'r12' : undeclared identifier
    src/multiply_32.c(88) : error C2065: 'r13' : undeclared identifier
    src/multiply_32.c(88) : error C2065: 'r14' : undeclared identifier
    src/multiply_32.c(88) : error C2065: 'r15' : undeclared identifier
    src/multiply_32.c(88) : error C2065: 'r16' : undeclared identifier
    src/multiply_32.c(88) : error C2065: 'r17' : undeclared identifier
    src/multiply_32.c(90) : error C2065: 'r10' : undeclared identifier
    src/multiply_32.c(90) : error C2164: '_mm_shuffle_epi32' : intrinsic function not declared
    src/multiply_32.c(91) : error C2164: '_mm_castpd_si128' : intrinsic function not declared
    src/multiply_32.c(92) : error C2164: '_mm_set_sd' : intrinsic function not declared
    src/multiply_32.c(93) : error C2284: '_mm_castpd_si128': illegal argument to intrinsic function, parameter 1
    src/multiply_32.c(93) : fatal error C1903: unable to recover from previous error(s); stopping compilation
    error: command 'C:\\Program Files\\Common Files\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2
```

**Comment by alxchk** [comment] 2018-11-29 09:51
Last working release is 3.7.0.

For me latest release from pip break both windows and linux builds. Both use old compilers without intrins.

Maybe it's worth to add some build flag,  define or envvar to support such systems?

**Comment by Legrandin** [comment] 2018-11-29 10:20
Thanks for reporting. Can you confirm you see this in 3.7.2? And possibly provide the entire build log?
For instance, this is the one for MSVC 9.0 on a 32-bit Windows (like in your case):

https://ci.appveyor.com/project/Legrandin/pycryptodome/build/job/a78ju8ppxm5bqg5a?fullLog=true

but there it works fine.

There is logic to autodetect compiler and platform features, including support for intrinsics (see `compiler_opt.p`): I would rather fix that and avoid explicit build flags.

**Comment by alxchk** [comment] 2018-11-29 10:30
I'll check 3.7.2 (or git master).

In my case I use a bit non-standard environment. For example - cl from msvs and headers from DDK. Same story for linux (gcc and headers from Debian etch)

**Comment by alxchk** [comment] 2018-11-29 10:39
```
    Running setup.py install for pycryptodome: finished with status 'error'
    Complete output from command C:\Python27\python.exe -u -c "import setuptools, tokenize;__file__='C:\\users\\root\\temp\\pip-req-build-8zqgcg\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\users\root\temp\pip-record-zrp8ko\install-record.txt --single-version-externally-managed --compile:
    Testing support for clang
    cl : Command line warning D9025 : overriding '/O1' with '/Ox'
    test1.c
    build\test1.c(3) : fatal error C1189: #error :  Not clang
    Target does not support clang
    Testing support for gcc
    cl : Command line warning D9025 : overriding '/O1' with '/Ox'
    test1.c
    build\test1.c(3) : fatal error C1189: #error :  Not GCC
    Target does not support gcc
    Testing support for stdint.h header
    cl : Command line warning D9025 : overriding '/O1' with '/Ox'
    test1.c
    build\test1.c(2) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
    Target does not support stdint.h header
    Testing support for 128-bit integer
    cl : Command line warning D9025 : overriding '/O1' with '/Ox'
    test1.c
    build\test1.c(4) : error C2065: '__uint128_t' : undeclared identifier
    build\test1.c(4) : error C2146: syntax error : missing ';' before identifier 'x'
    build\test1.c(4) : error C2065: 'x' : undeclared identifier
    Target does not support 128-bit integer
    Testing support for intrin.h header
    cl : Command line warning D9025 : overriding '/O1' with '/Ox'
    test1.c
    Generating code
    c:\users\root\temp\pip-req-build-8zqgcg\build\test1.c(6) : warning C4700: uninitialized local variable 'a' used
    Finished generating code
    Target does not support intrin.h header
    Testing support for cpuid.h header
    cl : Command line warning D9025 : overriding '/O1' with '/Ox'
    test1.c
    build\test1.c(2) : fatal error C1083: Cannot open include file: 'cpuid.h': No such file or directory
    Target does not support cpuid.h header
    Testing support for posix_memalign
    cl : Command line warning D9025 : overriding '/O1' with '/Ox'
    test1.c
    build\test1.c(5) : warning C4013: 'posix_memalign' undefined; assuming extern returning int
    Target does support posix_memalign
    Testing support for SSE2
    cl : Command line warning D9025 : overriding '/O1' with '/Ox'
    test1.c
    Target does support SSE2
    Warning: compiler does not support AESNI instructions
    Warning: compiler does not support CLMUL instructions
    running install
    running build
    running build_py
```

```
    C:\Program Files\Common Files\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DPYCRYPTO_LITTLE_ENDIAN -DLTC_NO_ASM -DHAVE_POSIX_MEMALIGN -DUSE_SSE2 -Isrc/ -IC:\Python27\include -IC:\Python27\PC /Tcsrc/multiply_32.c /Fobuild\temp.win32-2.7\Release\src/multiply_32.obj
    cl : Command line warning D9025 : overriding '/O1' with '/Ox'
    multiply_32.c
    src/multiply_32.c(69) : error C2065: '__m128i' : undeclared identifier
    src/multiply_32.c(69) : error C2146: syntax error : missing ';' before identifier 'r0'
    src/multiply_32.c(69) : error C2065: 'r0' : undeclared identifier
    src/multiply_32.c(69) : error C2065: 'r1' : undeclared identifier
    src/multiply_32.c(84) : error C2065: 'r0' : undeclared identifier
    src/multiply_32.c(84) : error C2164: '_mm_set1_epi32' : intrinsic function not declared
    src/multiply_32.c(85) : error C2065: 'r1' : undeclared identifier
    src/multiply_32.c(85) : error C2164: '_mm_cvtsi32_si128' : intrinsic function not declared
    src/multiply_32.c(88) : error C2065: '__m128i' : undeclared identifier
    src/multiply_32.c(88) : error C2146: syntax error : missing ';' before identifier 'r10'
    src/multiply_32.c(88) : error C2065: 'r10' : undeclared identifier
    src/multiply_32.c(88) : error C2065: 'r11' : undeclared identifier
    src/multiply_32.c(88) : error C2065: 'r12' : undeclared identifier
    src/multiply_32.c(88) : error C2065: 'r13' : undeclared identifier
    src/multiply_32.c(88) : error C2065: 'r14' : undeclared identifier
    src/multiply_32.c(88) : error C2065: 'r15' : undeclared identifier
    src/multiply_32.c(88) : error C2065: 'r16' : undeclared identifier
    src/multiply_32.c(88) : error C2065: 'r17' : undeclared identifier
    src/multiply_32.c(90) : error C2065: 'r10' : undeclared identifier
    src/multiply_32.c(90) : error C2164: '_mm_shuffle_epi32' : intrinsic function not declared
    src/multiply_32.c(91) : error C2164: '_mm_castpd_si128' : intrinsic function not declared
    src/multiply_32.c(92) : error C2164: '_mm_set_sd' : intrinsic function not declared
    src/multiply_32.c(93) : error C2284: '_mm_castpd_si128': illegal argument to intrinsic function, parameter 1
    src/multiply_32.c(93) : fatal error C1903: unable to recover from previous error(s); stopping compilation
    error: command 'C:\\Program Files\\Common Files\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2
    
    ----------------------------------------
  Rolling back uninstall of pycryptodome
Command "C:\Python27\python.exe -u -c "import setuptools, tokenize;__file__='C:\\users\\root\\temp\\pip-req-build-8zqgcg\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\users\root\temp\pip-record-zrp8ko\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\users\root\temp\pip-req-build-8zqgcg\
```

**Comment by Legrandin** [comment] 2018-12-01 08:46
@alxchk I added a small check (on master branch only) which hopefully can get you past the build step.
Also, if you now set an environment variable `PYCRYPTODOME_DEBUG`, you will get more error messages, though not no Windows.

However, I am only second guessing what's happening in your system. If it's really a combination of compilers and include files coming from different places (i.e. not a standard distro) that I can't reproduce, I am able to only invest so much time in fixing the problem.

For instance, in the logs you pasted last, I see that somehow MSVC manages to compile a small program that includes `intrin.h` and later it doesn't, which is very puzzling.

**Comment by alxchk** [comment] 2018-12-01 15:16
Build works for me for current master. 

I can't use the lib, but this may be some other issue. In case new issue is related to this one, Ill update

**Comment by Legrandin** [comment] 2019-03-22 19:48
Closing as it seems fixed.

**Closed by Legrandin** 2019-03-22 19:48 UTC
