### ISSUE TITLE
cffi cfparser uint8 error

### ISSUE THREAD

**Issue by 5l1v3r1** [Legrandin/pycryptodome#416] opened 2020-05-10 16:05 UTC
from Cryptodome.Cipher import ARC4
File "ginguma.py", line 31, in <module>
    import lib.ui.main
  File "/root/Desktop/inguma-kali-master/lib/ui/main.py", line 66, in <module>
    import lib.ui.core as core
  File "/root/Desktop/inguma-kali-master/lib/ui/core.py", line 28, in <module>
    import scapy.all as scapy
  File "/root/Desktop/inguma-kali-master/scapy/all.py", line 38, in <module>
    from layers.all import *
  File "/root/Desktop/inguma-kali-master/scapy/layers/all.py", line 16, in <module>
    _import_star(_l)
  File "/root/Desktop/inguma-kali-master/scapy/layers/all.py", line 10, in _import_star
    mod = __import__(m, globals(), locals())
  File "/root/Desktop/inguma-kali-master/scapy/layers/dot11.py", line 17, in <module>
    from Cryptodome.Cipher import ARC4
  File "/usr/local/lib/python2.7/dist-packages/Cryptodome/Cipher/__init__.py", line 27, in <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "/usr/local/lib/python2.7/dist-packages/Cryptodome/Cipher/_mode_ecb.py", line 29, in <module>
    from Cryptodome.Util._raw_api import (load_pycryptodome_raw_lib,
  File "/usr/local/lib/python2.7/dist-packages/Cryptodome/Util/_raw_api.py", line 88, in <module>
    uint8_t_type = ffi.typeof(ffi.new("const uint8_t*"))
  File "/usr/lib/python2.7/dist-packages/cffi/api.py", line 266, in new
    cdecl = self._typeof(cdecl)
  File "/usr/lib/python2.7/dist-packages/cffi/api.py", line 186, in _typeof
    result = self._typeof_locked(cdecl)
  File "/usr/lib/python2.7/dist-packages/cffi/api.py", line 171, in _typeof_locked
    type = self._parser.parse_type(cdecl)
  File "/usr/lib/python2.7/dist-packages/cffi/cparser.py", line 520, in parse_type
    return self.parse_type_and_quals(cdecl)[0]
  File "/usr/lib/python2.7/dist-packages/cffi/cparser.py", line 523, in parse_type_and_quals
    ast, macros = self._parse('void __dummy(\n%s\n);' % cdecl)[:2]
  File "/usr/lib/python2.7/dist-packages/cffi/cparser.py", line 307, in _parse
    self.convert_pycparser_error(e, csource)
  File "/usr/lib/python2.7/dist-packages/cffi/cparser.py", line 336, in convert_pycparser_error
    raise CDefError(msg)
cffi.CDefError: parse error
<cdef automatic initialization code>:1:13: before: uint8_t

**Comment by texadactyl** [comment] 2020-05-10 16:41
It is very hard to read this issue statement.  Where is your source code?  What were you trying to do?

Are you saying that ```from Cryptodome.Cipher import ARC4``` causes this cascade to "cffi.CDefError: parse error"?  If so, I cannot reproduce that in either Python 2 (DEPRECATED) or Python 3.

**Comment by Legrandin** [comment] 2022-12-12 21:29
Closing due to lack on feedback.

**Closed by Legrandin** 2022-12-12 21:29 UTC
